name: Publish Factorio Mod

on:
  push:
    branches:
      - publish

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Check out repository
        uses: actions/checkout@v3

      # Version aus info.json auslesen
      - name: Extract version from info.json
        id: get_version
        run: |
          VERSION=$(grep '"version":' info.json | sed -E 's/.*"version": "([^"]+)".*/\1/')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # Mod packen mit korrektem Verzeichnisaufbau
      - name: Pack Factorio Mod
        run: |
          FOLDER_NAME="player-auto-build-2_${VERSION}"
          mkdir $FOLDER_NAME
          mv !($FOLDER_NAME|.git|.github) $FOLDER_NAME
          ZIP_NAME="${FOLDER_NAME}.zip"
          zip -r $ZIP_NAME $FOLDER_NAME
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

      # Initialisiere Upload
      - name: Initialize Upload
        id: init_upload
        env:
          FACTORIO_MOD_TOKEN: ${{ secrets.FACTORIO_MOD_TOKEN }}
          MOD_NAME: "player-auto-build-2"
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer $FACTORIO_MOD_TOKEN" \
            -F "mod=$MOD_NAME" \
            https://mods.factorio.com/api/v2/mods/releases/init_upload)
          echo $RESPONSE > init_upload_response.json
          if ! grep -q '"upload_url":' init_upload_response.json; then
            echo "init_upload failed: $RESPONSE"
            exit 1
          fi
          UPLOAD_URL=$(cat init_upload_response.json | jq -r '.upload_url')
          echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITHUB_ENV

      # Datei hochladen
      - name: Upload Mod
        env:
          UPLOAD_URL: ${{ env.UPLOAD_URL }}
        run: |
          curl -s -X POST \
            -F "file=@$ZIP_NAME" \
            "$UPLOAD_URL" > upload_response.json
          if ! grep -q '"success":true' upload_response.json; then
            echo "Upload failed: $(cat upload_response.json)"
            exit 1
          fi
          echo "Upload successful!"
